trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
    displayName: 'Install Ruby and other dependencies'

  - script: sudo gem install bundler
    displayName: 'Install Bundler'

  - script: bundle install
    displayName: 'Install all of the required gems'

  - script: bundle config build.nokogiri --use-system-libraries
    displayName: 'Config nokogiri to build using system libraries'

  - script: bundle exec rake book:build
    displayName: 'Generate the books'

  - task: CopyFiles@2
    inputs:
      contents: '_buildOutput/**'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    displayName: Publish generated books
    inputs:
      pathtoPublish: build-output/
      artifactName: progit2
      publishLocation: container